### ISSUE TITLE
 Can tetua be used as a forum?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ngocphuongnb/tetua#1] opened 2022-05-16 09:14 UTC
tetua is cool, can he be used as a forum? Does it have a normal user registration function and posting function? Or only admins can post and normal users can only view and comment?

**Comment by ngocphuongnb** [comment] 2022-05-16 12:21
@Yakumo-Yukari thank you for spend your time on Tetua.
Tetua isn't suppose to be a forum, but it's main features seem to fit your describe:
- Tetua allow users to create a post
- Currently, only Github is support for the user login, but i am working on a release that allow user login via email or other social networks

Please take a look at tetua.net and if there are features that was missing, don't hesitate to tell me

**Comment by waiducom** [comment] 2022-05-16 12:40
hello，Why can't I log in, the username and password are both correct. for v0.04

**Comment by ngocphuongnb** [comment] 2022-05-17 00:04
@waiducom can you show me the error message or post the log here?

**Comment by waiducom** [comment] 2022-05-17 00:32
@[ngocphuongnb](https://github.com/ngocphuongnb)

`2022-05-17T08:30:26.235686804+08:00     info    middlewares/request.go:42       Request completed       {"request_id": "c8583496-3740-458c-9efd-72d4dbe5b98b", "latency": "2ms", "status": 200, "method": "GET", "path": "/", "ip": "192.168.1.2"}
2022-05-17T08:30:27.483667395+08:00     info    middlewares/request.go:42       Request completed       {"request_id": "7ad53e30-d65c-423b-a3e5-d3a39230864b", "latency": "0s", "status": 404, "method": "GET", "path": "/favicon.ico", "ip": "192.168.1.2"}
2022-05-17T08:30:28.702052007+08:00     info    middlewares/request.go:42       Request completed       {"request_id": "f15581e2-8356-44e8-b120-993effe01f75", "latency": "0s", "status": 200, "method": "GET", "path": "/login", "ip": "192.168.1.2"}
2022-05-17T08:30:35.86316114+08:00      info    middlewares/request.go:42       Request completed       {"request_id": "0fe5d152-f020-4af2-9228-467ad5c61739", "status": 302, "method": "POST", "path": "/login", "ip": "192.168.1.2", "latency": "105ms"}
2022-05-17T08:30:36.090492092+08:00     info    middlewares/request.go:42       Request completed       {"request_id": "c03c1779-ebef-4ca2-b4aa-0185756e87d1", "method": "GET", "path": "/", "ip": "192.168.1.2", "latency": "2ms", "status": 200}`

**Comment by ngocphuongnb** [comment] 2022-05-17 03:15
@waiducom I tested with the latest release and can't made your bug happen.
From your login request log:
```json
{
  "request_id": "0fe5d152-f020-4af2-9228-467ad5c61739",
  "status": 302,
  "method": "POST",
  "path": "/login",
  "ip": "192.168.1.2",
  "latency": "105ms"
}
```
The request completed with the status `302`, and based on the login code, there are two cases that will return the `302` status:

**The current login user is not root and the account is inactive**
In this case, the user will be redirected to the page `/inactive`
```go
if !foundUsers[0].IsRoot() && !foundUsers[0].Active {
  return c.Redirect(config.Url("/inactive"))
}
```

**The login was sucess**
In this case, the user will be redirected to the home page
```go
return c.Redirect(config.Url(""))
```
As the user you are login was created from the `setup command`, it's root and is activated by default.
From your screenshot, you are not in the `/inactive` page, so i think the login was success and it was redirected to the home page as expected.

Please check if  your browser cookie is enabled, and also check for the Tetua cookie on your browser to see if it's existed.

**Comment by ego008** [comment] 2022-05-17 03:53
> hello，Why can't I log in, the username and password are both correct. for v0.04
> 

It's work well after running `./tetua setup -u admin -p admin` for me.

<img width="1130" alt="2022-05-17 11 47 43" src="https://user-images.githubusercontent.com/47590/168725155-077d7f05-7d9d-4c8b-8153-bbdf0a23411e.png">

**Comment by waiducom** [comment] 2022-05-17 05:23
@[ego008](https://github.com/ego008). [ngocphuongnb](https://github.com/ngocphuongnb)
Wǒ bù zhīdào wèntí chūxiàn zài nǎ? Shǐyòng de shì biānyì hǎo de zhíxíng wénjiàn, xìtǒng wèi Debian 11.
37 / 5,000
翻译结果
I don't know where is the problem? The compiled executable file is used, and the system is Debian 11.

**Comment by waiducom** [comment] 2022-05-17 05:48
@ngocphuongnb [ngocphuongnb](https://github.com/ngocphuongnb).  
The problem is solved, it is caused by the mysql problem, mainly when the mysql table is not created when the database is initialized.

**Comment by ngocphuongnb** [comment] 2022-05-17 06:28
@waiducom that's good. I'm downloading virtualbox and Debian 11 image to debug but the internet speed is low.
Do you know why the table wasn't created? I want to make Tetua easy to use, so your sharing is important. Thank you!

**Comment by ngocphuongnb** [comment] 2022-05-17 06:29
@ego008 thank you, if you need any help, please fire an issue.

**Comment by waiducom** [comment] 2022-05-17 07:51
@[ngocphuongnb](https://github.com/ngocphuongnb). 

I don't know why the table is not created, it may be the mysql version, or the space, or other reasons. It's a great program, and I hope it's easy for everyone to use, like @ego008's goyoubbs tires program. At present, there are two problems found, the user avatar cannot be uploaded, the article is published, the title cannot be entered, and the title input box is gray~

**Comment by waiducom** [comment] 2022-05-17 07:54
There is another problem. If you use the public network IP to access, you will not be able to log in to the background. You can only access it normally through the front-end nginx or apache proxy. At present, these bugs have been found

**Comment by waiducom** [comment] 2022-05-17 07:59
Recommend to try goleveldb as a database or not mysql, like ego008's goyoubbs tire program, it's great

**Comment by waiducom** [comment] 2022-05-17 08:06
errors log:

`{"level":"error","ts":"2022-05-17T16:05:17.385289792+08:00","caller":"fiberserver/context.go:195","msg":"Error saving avatar image","request_id":"f62f55fe-82a9-4167-b43b-47a93d1726b4","0":"file type is not allowed","stacktrace":"github.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).WithError\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:195\ngithub.com/ngocphuongnb/tetua/app/web/setting.getSettingSaveData\n\t/home/ngocphuongnb/projects/tetua/app/web/setting/setting.go:111\ngithub.com/ngocphuongnb/tetua/app/web/setting.Save\n\t/home/ngocphuongnb/projects/tetua/app/web/setting/setting.go:31\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func2.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:23\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/auth.Check\n\t/home/ngocphuongnb/projects/tetua/app/auth/middlewares.go:35\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/middlewares.Cookie\n\t/home/ngocphuongnb/projects/tetua/app/middlewares/cookie.go:23\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/middlewares.RequestLog\n\t/home/ngocphuongnb/projects/tetua/app/middlewares/request.go:28\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/middlewares.Recover\n\t/home/ngocphuongnb/projects/tetua/app/middlewares/recover.go:29\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/auth.AssignUserInfo\n\t/home/ngocphuongnb/projects/tetua/app/auth/middlewares.go:98\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:789\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.(*Context).Next\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/context.go:170\ngithub.com/ngocphuongnb/tetua/app/middlewares.RequestID\n\t/home/ngocphuongnb/projects/tetua/app/middlewares/request.go:23\ngithub.com/ngocphuongnb/tetua/packages/fiberserver.transformHandlers.func1.1\n\t/home/ngocphuongnb/projects/tetua/packages/fiberserver/utils.go:15\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:792\ngithub.com/gofiber/fiber/v2/middleware/compress.New.func3\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/middleware/compress/compress.go:54\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*App).handler\n\t/home/ngocphuongnb/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:160\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\t/home/ngocphuongnb/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\t/home/ngocphuongnb/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\t/home/ngocphuongnb/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196"}
{"level":"info","ts":"2022-05-17T16:05:17.517294779+08:00","caller":"middlewares/request.go:42","msg":"Request completed","request_id":"f62f55fe-82a9-4167-b43b-47a93d1726b4","latency":"132ms","status":200,"method":"POST","path":"/settings","ip":"127.0.0.1"}`

**Comment by Yakumo-Yukari** [comment] 2022-05-17 08:52
> @Yakumo-Yukari thank you for spend your time on Tetua. Tetua isn't suppose to be a forum, but it's main features seem to fit your describe:
> 
> * Tetua allow users to create a post
> * Currently, only Github is support for the user login, but i am working on a release that allow user login via email or other social networks
> 
> Please take a look at tetua.net and if there are features that was missing, don't hesitate to tell me

Thank you for your answer, tetua is a really good open source project very cool, finally have a good day

**Comment by Yakumo-Yukari** [comment] 2022-05-17 09:31
@ngocphuongnb After logging into https://tetua.net with github, posts and comments prompt 'Insufficient permission'

**Comment by ngocphuongnb** [comment] 2022-05-17 10:04
@Yakumo-Yukari thank you for your report. I'm checking the permissions for the user group.

**Comment by ngocphuongnb** [comment] 2022-05-17 11:36
@Yakumo-Yukari the issue had been fixed here: https://github.com/ngocphuongnb/tetua/commit/6d44eadbfc6624a6071251a27f11c543004e5ed8
Please try again with the latest release version https://github.com/ngocphuongnb/tetua/releases/tag/v0.0.5-alpha
Thank you!

**Comment by ego008** [comment] 2022-05-17 15:10
@waiducom You can open a **new** issue for a different question.

> new bug ,When I log in successfully for the first time, after logging out and logging in again, there will be an error
> 
> Username and password are correct

Because you didn't clear the content of the `Password` field on the `/settings` page, then you clicked the `Save` button.

Now you can try update user `password` in mysql to fix it, new password is `admin` after updated.

``` sql
mysql> update users set password='$argon2id$v=19$m=65536,t=3,p=4$HbOLgeIhdziyPa8l3mb5OQ$2t+EksYZfSoWS55tuAK3xtxT4lbx3RfU2wnP3gsZLX8' where id=1;
```

@ngocphuongnb Set the `Password` field with blank as default for local account to fix this bug.

![2022-05-17 22 49](https://user-images.githubusercontent.com/47590/168843640-6b92c9ee-bf26-49a9-9836-90945a0074df.png)

**Comment by waiducom** [comment] 2022-05-17 15:15
> @waiducom You can open a **new** issue for a different question.
> 
> > new bug ,When I log in successfully for the first time, after logging out and logging in again, there will be an error
> > Username and password are correct
> 
> Because you didn't clear the content of the field on the page, then you clicked the button.`Password``/settings``Save`
> 
> Now you can try update user's in mysql to fix it, new password is after updated.`password``admin`
> 
> ```sql
> mysql> update users set password='$argon2id$v=19$m=65536,t=3,p=4$HbOLgeIhdziyPa8l3mb5OQ$2t+EksYZfSoWS55tuAK3xtxT4lbx3RfU2wnP3gsZLX8' where id=1;
> ```
> 
> @ngocphuongnb Set the field with blank as default for local account to fix this bug.`Password`
> 
> ![2022-05-17 22 49](https://user-images.githubusercontent.com/47590/168843640-6b92c9ee-bf26-49a9-9836-90945a0074df.png)

@ego008  Haha, speaking English, I'm not used to it!

**Comment by ngocphuongnb** [comment] 2022-05-17 23:05
@waiducom @ego008
This bug was fixed in this commit https://github.com/ngocphuongnb/tetua/commit/6d44eadbfc6624a6071251a27f11c543004e5ed8.
Please try with the latest release . Thank you!

**Comment by ngocphuongnb** [comment] 2022-05-18 04:03
I am going to close this issue. If you found any bugs, please create a new issue. Thanks!

**Closed by ngocphuongnb** 2022-05-18 04:03 UTC
